// 
// USB Keyboard Code
//   Tool Labs
//

#ifndef USBKEYCODE_H
#define USBKEYCODE_H

// Keyboard
#define KEYCODE_A						0x04
#define KEYCODE_B						0x05
#define KEYCODE_C						0x06
#define KEYCODE_D						0x07
#define KEYCODE_E						0x08
#define KEYCODE_F						0x09
#define KEYCODE_G						0x0a
#define KEYCODE_H						0x0b
#define KEYCODE_I						0x0c
#define KEYCODE_J						0x0d
#define KEYCODE_K						0x0e
#define KEYCODE_L						0x0f
#define KEYCODE_M						0x10
#define KEYCODE_N						0x11
#define KEYCODE_O						0x12
#define KEYCODE_P						0x13
#define KEYCODE_Q						0x14
#define KEYCODE_R						0x15
#define KEYCODE_S						0x16
#define KEYCODE_T						0x17
#define KEYCODE_U						0x18
#define KEYCODE_V						0x19
#define KEYCODE_W						0x1a
#define KEYCODE_X						0x1b
#define KEYCODE_Y						0x1c
#define KEYCODE_Z						0x1d
#define KEYCODE_1						0x1e
#define KEYCODE_2						0x1f
#define KEYCODE_3						0x20
#define KEYCODE_4						0x21
#define KEYCODE_5						0x22
#define KEYCODE_6						0x23
#define KEYCODE_7      					0x24
#define KEYCODE_8						0x25
#define KEYCODE_9						0x26
#define KEYCODE_0						0x27
#define KEYCODE_ReturnEnter				0x28
#define KEYCODE_Escape					0x29
#define KEYCODE_Delete					0x2a
#define KEYCODE_Tab						0x2b
#define KEYCODE_spacebar				0x2c
#define KEYCODE_Minus   				0x2d
#define KEYCODE_Equal					0x2e
#define KEYCODE_LeftSquareParen			0x2f
#define KEYCODE_RightSquareParen		0x30
#define KEYCODE_Yen						0x31
#define KEYCODE_NonusSharp				0x32
#define KEYCODE_SemiColon				0x33
#define KEYCODE_Colon					0x34
#define KEYCODE_GraveAccent				0x35
#define KEYCODE_Comma					0x36
#define KEYCODE_Period					0x37
#define KEYCODE_Slash					0x38
#define KEYCODE_CapsLock				0x39
#define KEYCODE_F1						0x3a
#define KEYCODE_F2						0x3b
#define KEYCODE_F3						0x3c
#define KEYCODE_F4						0x3d
#define KEYCODE_F5						0x3e
#define KEYCODE_F6						0x3f
#define KEYCODE_F7						0x40
#define KEYCODE_F8						0x41
#define KEYCODE_F9						0x42
#define KEYCODE_F10						0x43
#define KEYCODE_F11						0x44
#define KEYCODE_F12						0x45
#define KEYCODE_PrintScreen				0x46
#define KEYCODE_ScrollLock				0x47
#define KEYCODE_Pause					0x48
#define KEYCODE_Insert					0x49
#define KEYCODE_Home					0x4a
#define KEYCODE_PageUp					0x4b
#define KEYCODE_DeleteForward			0x4c
#define KEYCODE_End						0x4d
#define KEYCODE_PageDown				0x4e
#define KEYCODE_RightArrow				0x4f
#define KEYCODE_LeftArrow				0x50
#define KEYCODE_DownArrow				0x51
#define KEYCODE_UpArrow					0x52
#define KEYCODE_KeypadNumLock			0x53
#define KEYCODE_KeypadSlash				0x54
#define KEYCODE_KeypadAsterisk			0x55
#define KEYCODE_KeypadMinus				0x56
#define KEYCODE_KeypadPlus				0x57
#define KEYCODE_KeypadEnter				0x58
#define KEYCODE_Keypad1_End				0x59
#define KEYCODE_Keypad2_DownArrow		0x5a
#define KEYCODE_Keypad3_PageDown		0x5b
#define KEYCODE_Keypad4_LeftArrow		0x5c
#define KEYCODE_Keypad5					0x5d
#define KEYCODE_Keypad6_RightArrow		0x5e
#define KEYCODE_Keypad7_Home			0x5f
#define KEYCODE_Keypad8_UpArrow			0x60
#define KEYCODE_Keypad9_PageUp			0x61
#define KEYCODE_Keypad0_Insert			0x62
#define KEYCODE_KeypadPeriod			0x63
#define KEYCODE_NonusBackSlash			0x64
#define KEYCODE_Application				0x65
#define KEYCODE_Power					0x66
#define KEYCODE_KeypadEqual				0x67
#define KEYCODE_F13						0x68
#define KEYCODE_F14						0x69
#define KEYCODE_F15						0x6a
#define KEYCODE_F16						0x6b
#define KEYCODE_F17						0x6c
#define KEYCODE_F18						0x6d
#define KEYCODE_F19						0x6e
#define KEYCODE_F20						0x6f
#define KEYCODE_F21						0x70
#define KEYCODE_F22						0x71
#define KEYCODE_F23						0x72
#define KEYCODE_F24						0x73
#define KEYCODE_Execute					0x74
#define	KEYCODE_Help					0x75
#define KEYCODE_Menu					0x76
#define KEYCODE_Select					0x77
#define KEYCODE_Stop					0x78
#define KEYCODE_Again					0x79
#define KEYCODE_Undo					0x7a
#define KEYCODE_Cut						0x7b
#define KEYCODE_Copy					0x7c
#define KEYCODE_Paste					0x7d
#define KEYCODE_Find					0x7e
#define KEYCODE_Mute					0x7f
#define KEYCODE_VolumeUp				0x80
#define KEYCODE_VolumeDown				0x81
#define KEYCODE_LockingCapsLock			0x82
#define KEYCODE_LockingNumLock			0x83
#define KEYCODE_LockingScrollLock		0x84
#define KEYCODE_KeypadComma				0x85
#define KEYCODE_KeypadEqualSign			0x86
#define KEYCODE_International1			0x87
#define KEYCODE_International2			0x88
#define KEYCODE_International3			0x89
#define KEYCODE_International4			0x8a
#define KEYCODE_International5			0x8b
#define KEYCODE_International6			0x8c
#define KEYCODE_International7			0x8d
#define KEYCODE_International8			0x8e
#define KEYCODE_International9			0x8f
#define KEYCODE_Lang1					0x90
#define KEYCODE_Lang2					0x91
#define KEYCODE_Lang3					0x92
#define KEYCODE_Lang4					0x93
#define KEYCODE_Lang5					0x94
#define KEYCODE_Lang6					0x95
#define KEYCODE_Lang7					0x96
#define KEYCODE_Lang8					0x97
#define KEYCODE_Lang9					0x98
#define KEYCODE_AlternateErase			0x99
#define KEYCODE_SysReq					0x9a
#define KEYCODE_Cancel					0x9b
#define KEYCODE_Clear					0x9c
#define KEYCODE_Prior					0x9d
#define KEYCODE_Return					0x9e
#define KEYCODE_Separator				0x9f
#define KEYCODE_Out						0xa0
#define KEYCODE_Oper					0xa1
#define KEYCODE_ClearAgain				0xa2
#define KEYCODE_CrSelProps				0xa3
#define KEYCODE_ExSel					0xa4
#define KEYCODE_Keypad00				0xb0
#define KEYCODE_Keypad000				0xb1
#define KEYCODE_ThousandsSeparator		0xb2
#define KEYCODE_DecimalSeparator		0xb3
#define KEYCODE_CurrencyUnit			0xb4
#define KEYCODE_CurrencySubunit			0xb5
#define KEYCODE_KeypadLeftParen			0xb6
#define KEYCODE_KeypadRightParen		0xb7
#define KEYCODE_KeypadBrace				0xb8
#define KEYCODE_KeypadRightBrace		0xb9
#define KEYCODE_KeypadTab				0xba
#define KEYCODE_KeypadBackSpace			0xbb
#define KEYCODE_KeypadA					0xbc
#define KEYCODE_KeypadB					0xbd
#define KEYCODE_KeypadC					0xbe
#define KEYCODE_KeypadD					0xbf
#define KEYCODE_KeypadE					0xc0
#define KEYCODE_KeypadF					0xc1
#define KEYCODE_KeypadXOR				0xc2
#define KEYCODE_KeypadHat				0xc3
#define KEYCODE_KeypadPercent			0xc4
#define KEYCODE_KeypadLessThan          0xc5
#define KEYCODE_KeypadLargerThan		0xc6
#define KEYCODE_KeypadAmpersand			0xc7
#define KEYCODE_KeypadDoubleAmpersand	0xc8
#define KEYCODE_KeypadBar           	0xc9
#define KEYCODE_KeypadDoubleBar			0xca
#define KEYCODE_KeypadColon				0xcb
#define KEYCODE_KeypadSharp				0xcc
#define KEYCODE_KeypadSpace				0xcd
#define KEYCODE_KeypadAtmark			0xce
#define KEYCODE_KeypadExclamation		0xcf
#define KEYCODE_KeypadMemoryStore		0xd0
#define KEYCODE_KeypadMemoryRecall		0xd1
#define KEYCODE_KeypadMemoryClear		0xd2
#define KEYCODE_KeypadMemoryAdd			0xd3
#define KEYCODE_KeypadMemorySubtract	0xd4
#define KEYCODE_KeypadMemoryMultiply	0xd5
#define KEYCODE_KeypadMemoryDivide		0xd6
#define KEYCODE_KeypadChangeSign		0xd7
#define KEYCODE_KeypadClear				0xd8
#define KEYCODE_KeypadClearEntry		0xd9
#define KEYCODE_KeypadBinary			0xda
#define KEYCODE_KeypadOctal				0xdb
#define KEYCODE_KeypadDecimal			0xdc
#define KEYCODE_KeypadHexadecimal		0xdd
#define KEYCODE_LeftControl				0xe0
#define KEYCODE_LeftShift				0xe1
#define KEYCODE_LeftAlt					0xe2
#define KEYCODE_LeftGUI					0xe3
#define KEYCODE_RightControl			0xe4
#define KEYCODE_RightShift				0xe5
#define KEYCODE_RightAlt				0xe6
#define KEYCODE_RightGUI				0xe7

// Modifier
#define MODIFIER_NONE                   0x00
#define MODIFIER_Control                0x01
#define MODIFIER_Shift                  0x02
#define MODIFIER_Option                 0x04
#define MODIFIER_Command                0x08

#endif